# Generated by Django 4.2.1 on 2025-06-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50, verbose_name='Имя котика')),
                ('anons', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('full_text', models.TextField(verbose_name='Полное описание')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Котик',
                'verbose_name_plural': 'Котики',
            },
        ),
    ]
