# Generated by Django 4.2.1 on 2025-06-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
