# Generated by Django 4.2.1 on 2025-06-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_articles_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
